export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const FETCH = 'COUNTER/FETCH';
export const FETCH_SUCCESS = 'COUNTER/FETCH_SUCCESS';
export const FETCH_FAILURE = 'COUNTER/FETCH_FAILURE';
